import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "vite";
import { postCard } from "./scripts/layout.mjs";

// Puts the three newest articles on the homepage so it links straight to the blog posts (and stays fresh as posts are added)
const latestPosts = () => ({
  name: "latest-posts",
  transformIndexHtml(html) {
    if (!html.includes("<!--LATEST_POSTS-->")) return html;
    const posts = JSON.parse(readFileSync("content/posts.json", "utf8"))
      .sort((a, b) => b.date.localeCompare(a.date))
      .slice(0, 3);
    return html.replace(
      "<!--LATEST_POSTS-->",
      `<section class="home-blog" aria-labelledby="home-blog-title">
        <div class="container">
          <p class="label">From the blog</p>
          <h2 id="home-blog-title">Keep your bike in shape</h2>
          <div class="post-grid">${posts.map(postCard).join("")}
          </div>
          <p class="home-blog-more"><a class="btn btn-ghost" href="/blog">All articles</a></p>
        </div>
      </section>`,
    );
  },
});

// Blog pages are generated by scripts/build-blog.mjs before dev and build
const blog = Object.fromEntries(
  readdirSync("blog").map((f) => [`blog-${f.replace(".html", "")}`, resolve(__dirname, "blog", f)]),
);

export default defineConfig({
  plugins: [latestPosts()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        login: resolve(__dirname, "login.html"),
        dashboard: resolve(__dirname, "dashboard.html"),
        features: resolve(__dirname, "features.html"),
        how: resolve(__dirname, "how-it-works.html"),
        faq: resolve(__dirname, "faq.html"),
        ...blog,
      },
    },
  },
});
