import { readdirSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "vite";

// Blog pages are generated by scripts/build-blog.mjs before dev and build
const blog = Object.fromEntries(
  readdirSync("blog").map((f) => [`blog-${f.replace(".html", "")}`, resolve(__dirname, "blog", f)]),
);

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        login: resolve(__dirname, "login.html"),
        dashboard: resolve(__dirname, "dashboard.html"),
        features: resolve(__dirname, "features.html"),
        how: resolve(__dirname, "how-it-works.html"),
        faq: resolve(__dirname, "faq.html"),
        ...blog,
      },
    },
  },
});
